fix: add helpful error message to AssociationTree
Add helpful error message when trying to eager load "past" a polymorphic association. Currently, trying to eager load past a polymorphic association in the console receives

```
NoMethodError: undefined method `associations' for nil:NilClass
	from (irb):2
```

Which is difficult to diagnose.